### ISSUE TITLE
[Feature] ZRR-97: ChildBoard 삭제 후 Category 생성

### ISSUE THREAD

**Issue by doojoo9999** [TeamBDMJ/zziririt-back#101]
## Description
- 설명: ChildBoard 삭제 후 Category 생성
- 참조 해야하는 지라 티켓 : ZRR-97

## Todo
- [ ] ChildBoard 삭제
- [ ] ChildBoard로 관리되던 Category들을 CategoryName으로 변경

- [ ] Category
- [ ] 카테고리 단건 조회
- [ ] 카테고리 전체 조회
- [ ] 카테고리 이름 변경
- [ ] BoardId가 가진 카테고리 전체 조회
- [ ] Board 생성 시 기본 카테고리 2개 제공 (공지 사항, 자유 게시판)

- [ ] BoardEntity
- [ ] parent (부모 게시판 삭제)

## ETC
- 고려해야할 점..
