### ISSUE TITLE
[Refactor] ZRR-103: 게시판 아이디 활용 하위 카테고리 조회 api, 카테고리 테이블에 들어가던 null 수정, 비활성화 게시판에 게시글이 등록되면 게시판 활성화

### ISSUE THREAD

**Issue by miso1105** [TeamBDMJ/zziririt-back#118]
## Description
- 설명: 게시판 아이디 활용 하위 카테고리 조회 api, 카테고리 테이블에 들어가던 null 수정,비활성화 게시판에 게시글이 등록되면 게시판 활성화
- 참조 해야하는 지라 티켓 : ZRR-103

## Todo
- [x] 게시판 아이디 활용 하위 카테고리 조회 api 작성
- [x] 카테고리 테이블에 들어가던 null 수정
- [x] 비활성화 게시판에 게시글이 등록되면 게시판 다시 활성화되도록 작성

## ETC
- 고려해야할 점..
