### ISSUE TITLE
[Feature] ZRR-83: Point History 개발

### ISSUE THREAD

**Issue by miso1105** [TeamBDMJ/zziririt-back#81]
## Description
- 설명: 포인트 거래내역 API 작성
- 참조 해야하는 지라 티켓 : ZRR-83

## Todo
- [x] 아이콘 구매 내역 표시
- [x] 포인트 전송 내역 표시
- [x] 포인트 획득 내역 표시
- [x] 유저 본인이 사용한 내역 조회

## ETC
- 고려해야할 점..

**Comment by Moveuk** [comment]
히스토리 개발이 다른 브랜치로 이전됨에 따라 기존 브랜치가 close 되었습니다. #115
