### ISSUE TITLE
[Feature] ZRR-91: Icon, Member, Point 리팩토링

### ISSUE THREAD

**Issue by doojoo9999** [TeamBDMJ/zziririt-back#90]
## Description
- 설명: Icon, Member, Point Refactoring
- 참조 해야하는 지라 티켓 : ZRR-91

## Todo
- [x] Ban 만료 시간이 지나면 MemberStatus를 VIEWER로 변경하는 스케쥴러 추가
- [x] RequestPart 수정 (백오피스에서 보내는 request 형식에 따라 수정)
- [x] Member에게 Icon을 지급하는 API 추가
- [x] PreAuthorize를 통한 Role 체크
- [x] RequestPart 수정 (백오피스에서 보내는 request 형식에 따라 수정)
- [x] PreAuthorize를 통한 Role 체크
- [x] Member Point 증/차감 API 추가
- [x] loginHistory 재연결
- [x] MemberAwareAudit 이슈 해결

## ETC
- 고려해야할 점..
